"""add project agent outputs

Revision ID: 136cbea8f4fb
Revises: 14ae8bb59965
Create Date: 2026-07-11 23:29:58.085070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '136cbea8f4fb'
down_revision: Union[str, Sequence[str], None] = '14ae8bb59965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('ceo_analysis', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('technical_architecture', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('prd', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('design', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('marketing', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('investment', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'investment')
    op.drop_column('projects', 'marketing')
    op.drop_column('projects', 'design')
    op.drop_column('projects', 'prd')
    op.drop_column('projects', 'technical_architecture')
    op.drop_column('projects', 'ceo_analysis')
    # ### end Alembic commands ###
