"""add project progress fields

Revision ID: 15b500ee7cf4
Revises: 136cbea8f4fb
Create Date: 2026-07-12 14:12:33.820702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15b500ee7cf4'
down_revision: Union[str, Sequence[str], None] = '136cbea8f4fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('current_agent', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('progress', sa.Integer(), nullable=False))
    op.add_column('projects', sa.Column('error_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'error_message')
    op.drop_column('projects', 'progress')
    op.drop_column('projects', 'current_agent')
    # ### end Alembic commands ###
